packages:
  - apps/*
  - packages/*

catalog:
  '@types/node': 24.1.0
  eslint: ^9.32.0
  prettier: ^3.6.2
  prettier-plugin-sql: 0.19.2
  shellcheck: ^3.1.0
  tsup: ^8.5.0
  typescript: ^5.9.2

dangerouslyAllowAllBuilds: false

ignoredBuiltDependencies:
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - esbuild
  - msw
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - '@snaplet/seed'
  - '@vercel/speed-insights'
  - supabase
