packages:
  - apps/**
  - packages/**

catalog:
  '@types/node': ^24.0.3
  eslint: ^9.29.0
  prettier: ^3.6.0
  release-it: ^19.0.3
  shellcheck: ^3.1.0
  tsup: ^8.5.0
  typescript: ^5.8.3

dangerouslyAllowAllBuilds: false

ignoredBuiltDependencies:
  - msw

onlyBuiltDependencies:
  - supabase
