packages:
  - apps/*
  - packages/*

catalog:
  "@types/node": ^22.14.0
  eslint: ^9.24.0
  prettier: ^3.5.3
  release-it: ^18.1.2
  shellcheck: ^3.1.0
  tsup: ^8.4.0
  typescript: ^5.8.3

ignoredBuiltDependencies:
  - msw

onlyBuiltDependencies:
  - "@vercel/speed-insights"
  - sharp
