name: CI
permissions:
  contents: read
  pull-requests: read
env:
  SHELLCHECKJS_LOGGER_LEVEL: warn
  NEXT_TELEMETRY_DISABLED: true
  TURBO_TELEMETRY_DISABLED: true
  SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
  SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/${{ vars.APP_PATH }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-
      - name: Install Corepack
        run: |
          npm install -g corepack@latest
          echo ./node_modules/.bin >> $GITHUB_PATH
          corepack enable
          corepack install
      - name: Install and build dependencies
        run: |
          pnpm install --no-frozen-lockfile
          pnpm build:packages
      - name: Run commitlint on push
        if: github.event_name == 'push'
        run: commitlint --last --verbose
      - name: Run commitlint on pull request
        if: github.event_name == 'pull_request' && github.actor != 'dependabot[bot]'
        run: commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
      - run: pnpm check
