name: CI
on:
  push:
    branches:
      - main
    tags:
      - v*
      - v*.*
      - v*.*.*
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]
permissions:
  actions: write
  checks: write
  contents: read
  pull-requests: read
env:
  NEXT_TELEMETRY_DISABLED: true
  TURBO_TELEMETRY_DISABLED: true
  SHELLCHECKJS_LOGGER_LEVEL: warn
  SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
  SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up cache
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - name: Install pnpm
        run: |
          npm install -g corepack@latest
          echo ./node_modules/.bin >> $GITHUB_PATH
          corepack enable
          corepack install
      - name: Install and build dependencies
        run: |
          pnpm install --no-frozen-lockfile
          pnpm build:packages
      - name: Run commitlint on push
        if: github.event_name == 'push'
        run: commitlint --last --verbose
      - name: Run commitlint on pull request
        if: github.event_name == 'pull_request' && github.actor != 'dependabot[bot]'
        run: commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
      - run: pnpm check
      - name: Run deployment
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        run: gh workflow run deploy.yml
        env:
          GH_TOKEN: ${{ github.token }}
